apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc 
  labels:
    app.kubernetes.io/name: mongo
spec:
  resources:
    requests:
      storage: 4Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: standard