apiVersion: v1
kind: Pod
metadata:
  name: webapp-config
  labels:
    app.kubernetes.io/name: color
spec:
  containers:
  - name: webapp
    image: mmumshad/simple-webapp-color
    ports:
      - containerPort: 8080
    env:
     - name: APP_COLOR
       valueFrom: 
        configMapKeyRef:
          name: color-config
          key: COLOR
